### ISSUE TITLE
Playlist Sidebar

### ISSUE THREAD

**Issue by RamiEjailat** [EvHaus/youtube-hide-watched#100]
When watching a video from a playlist (/watch?v=___&list=___), the videos (ytd-playlist-panel-video-renderer) in the playlist sidebar are currently not being handled.

The playlist sidebar is more prominent and more useful the regular sidebar in the case when watching a video from a playlist. What do you think?

**Comment by EvHaus** [comment]
This behaviour is intentional. There's no way for me to skip watched videos in a playlist. YouTube will play them anyway, so if it doesn't appear in the sidebar lister I think that would be weird.

Imagine you are you are watching a playlist and the next video that will play in the playlist is something you've already watched, I think it makes sense to still show it. Otherwise the video will play next but it won't appear in the list.

**Comment by RamiEjailat** [comment]
I suggest to add a toggle button on the playlist sidebar with just 2 options:
- Show all videos
- Display watched videos as dimmed

**Comment by EvHaus** [comment]
I think dimming the videos in there makes sense to me! I just published version 4.4.0 that adds this feature.

**Comment by RamiEjailat** [comment]
Thanks for your prompt response! I have just tested it and it's working well.
