### ISSUE TITLE
Works everywhere but doesnt work on Recommendations sidebar when watching a video

### ISSUE THREAD

**Issue by mato200** [EvHaus/youtube-hide-watched#78]
Latest Firefox

**Comment by adfaklsdjf** [comment]
I'm not seeing the `<ytd-thumbnail-overlay-resume-playback-renderer>` element in my Recommendations sidebar at all anymore... it will be present on a video in a playlist, but not present on the same video in the sidebar suggestions when viewing a video.

I checked the markup in Brave, then did a fresh login in Chromium with my ad blocker disabled and checked again.. still not present in the markup.  I only use 3 other extensions (Bitwarden, Tabs Outliner, Quick Javascript Switcher) and I'm confident they're not altering the markup.

I'm hoping this is a bug/regression on Youtube's side, because I've also noticed a huge spike in the amount of already-watched videos in my recommendations sidebar.

In my youtube cookie, the `PREF` value is `f4=4000000&tz=America.New_York&f6=40000000`, if that's of any value...

**Comment by EvHaus** [comment]
Thanks for submitting the issue. I'm having a hard time getting YouTube to show me any watched videos in the Recommendations sidebar. It seems like their algorithm already prefers only showing unwatched videos there. Any tips on how to get a watched video to show up there?

**Comment by adfaklsdjf** [comment]
I don't know.. I'm surprised you're not having the problem I'm having.. it's recommending me tons of watched videos and driving me crazy :(  It seems to particularly like recommending a video I just watched in the last day or so.  It definitely knows I've watched them.. the red bar shows in playlists and channel video lists.. just not in recommendations.

**Comment by netjeff** [comment]
Like @EvHaus, I'm not seeing any previously watched videos in my recommendations sidebar.  Hopefully just a glitch on YT's side for some users, like @adfaklsdjf, which they will fix soon.
